abertura = [
["FERNANDA SERAFIM AGUM", "Palestra de Abertura",],
["ANNE KAROLYNE ROCHA MIRANDA", "Palestra de Abertura",],
["RODRIGO TAVORA GADELHA", "Palestra de Abertura",],
["THIAGO LOPES FERREIRA", "Palestra de Abertura",],
["JANAINA BARBARA RANGEL SILVA", "Palestra de Abertura",],
["VITOR GUIMARÃES CORREIA", "Palestra de Abertura",],
["THAÍS CURVELLO DOS SANTOS", "Palestra de Abertura",],
["LEONARDO DE SOUSA MACHADO", "Palestra de Abertura",],
["JAYRLÂNDIA COUTINHO DE SOUZA", "Palestra de Abertura",],
["INÁCIA DE JESUS HENRIQUES GONÇALVES", "Palestra de Abertura",],
["MICHELLE MARIA FREITAS NETO", "Palestra de Abertura",],
["ESTHER SANTOS DA SILVA", "Palestra de Abertura",],
["ANA PAULA FERNANDES KLEM", "Palestra de Abertura",],
["RICARDO DE ALMEIDA CUNHA E OLIVEIRA TORRES", "Palestra de Abertura",],
["GUSTAVO LANDIM SOFFIATI", "Palestra de Abertura",],
["JULIANA SANTOS ALVES DE SOUZA", "Palestra de Abertura",],
["SUZANNE DE OLIVEIRA ROSÁRIO", "Palestra de Abertura",],
["ANETE RIBEIRO DA GAMA", "Palestra de Abertura",],
["MARIA EDUARDA MANHÃES PEREIRA", "Palestra de Abertura",],
["LUISA SILVA ROCHA", "Palestra de Abertura",],
["MARCELA RIBEIRO BARRETO", "Palestra de Abertura",],
["LUÍSA DA SILVA ALVES", "Palestra de Abertura",],
["ESDRAS DOS SANTOS", "Palestra de Abertura",],
["FLÁVIO JUNIO DE CARVALHO NETO", "Palestra de Abertura",],
["DARFINY ALVES NOGUEIRA", "Palestra de Abertura",],
["NATALIA LIMA NETTO", "Palestra de Abertura",],
["JULLYA BORGES DE SÁ", "Palestra de Abertura",],
["MÁRCIA HELENA DE OLIVEIRA MARTINS", "Palestra de Abertura",],
["MATHEUS SANTORIO MARQUES", "Palestra de Abertura",],
["DAYSE MARIA ALVES DE ANDRADE RIBEIRO", "Palestra de Abertura",],
["GIOVANA GANDRA RISCADO", "Palestra de Abertura",],
["RAIANY RAMOS ROSA", "Palestra de Abertura",],
["ABGAYL", "Palestra de Abertura",],
["MÍRIAN MARQUES DA SILVA", "Palestra de Abertura",],
["ELIZAMA PEREIRA DE SOUZA", "Palestra de Abertura",],
["LARA AZEREDO BRAZ", "Palestra de Abertura",],
["ANA ROSE FONSECA DA ROCHA DE MENEZES SANTOS", "Palestra de Abertura",],
["ISABELLA MOTA RAPHAEL DE LIMA ARÊAS", "Palestra de Abertura",],
["SILVANI BARRETO ASSUMPÇÃO CARDOSO", "Palestra de Abertura",],
["ANA CAROLINA LAURINDO PAULO", "Palestra de Abertura",],
["KETHELLIN BARRETO TEIXEIRA", "Palestra de Abertura",],
["ADRIANA LIMA DE SOUSA", "Palestra de Abertura",],
["VERA LÚCIA SOUZA DAS CHAGAS NOGUEIRA", "Palestra de Abertura",],
["JULIA MARQUES VELOSO FARIA", "Palestra de Abertura",],
["KELLY SILVA ANTUNES", "Palestra de Abertura",],
["ISABELLE GOMES", "Palestra de Abertura",],
["LUÍZA CASSIANO RANGEL", "Palestra de Abertura",],
["KARINA AZEREDO", "Palestra de Abertura",],
["FÁTIMA PEREIRA GOMES", "Palestra de Abertura",],
["JUVENAL NUNES DA SILVA NETO", "Palestra de Abertura",],
["RALF CRUZ MATEUS", "Palestra de Abertura",],
["MÁRCIO DE FREITAS AZEVEDO", "Palestra de Abertura",],
["MARIA LUIZA MARCHETTI DOS SANTOS", "Palestra de Abertura",],
["AÍDA MARIA JORGE RIBEIRO", "Palestra de Abertura",],
["MARCOS BRUNO PEREIRA CAMPOS", "Palestra de Abertura",],
["LUIZA APARECIDA FERREIRA BATISTA", "Palestra de Abertura",],
["SABRINA MENDONÇA FERREIRA", "Palestra de Abertura",],
["YASMIM BARBOSA PADILHA DE SOUZA", "Palestra de Abertura",],
["SAMUEL PEREIRA DE BRITO", "Palestra de Abertura",],
["NATIELEN NOGUEIRA RIBEIRO", "Palestra de Abertura",],
["CLISIVANIA DUARTE DE SOUZA", "Palestra de Abertura",],
["TALITA NEME LIMA SANTOS LOPES", "Palestra de Abertura",],
["ANTONIA CRISTINA BARCELOS FELIZARDO BARCELOS", "Palestra de Abertura",],
["ANGELLYNE MOÇO RANGEL", "Palestra de Abertura",],
["ISABELA GOMES DO NASCIMENTO", "Palestra de Abertura",],
["AMANDA MONTEIRO PINTO BARRETO", "Palestra de Abertura",],
["LUAN DE SOUZA FARIA", "Palestra de Abertura",],
["DICKSON MELO RODRIGUES", "Palestra de Abertura",],
["LETYCIA SARDINHA PEIXOTO MANHÃES", "Palestra de Abertura",],
["DOUGLAS GOMES SILVA DA CRUZ", "Palestra de Abertura",],
["REGIS BARRETO AMARAL", "Palestra de Abertura",],
["ROGÉRIO DE AVELLAR CAMPOS CORDEIRO", "Palestra de Abertura",],
["MARCOS ANDRÉ DA SILVA GOMES", "Palestra de Abertura",],
["SAULO QUEIROZ NASCIMENTO", "Palestra de Abertura",],
["REGINA MARIA PINHEIRO", "Palestra de Abertura",],
["ANA CAROLINA DO ROSÁRIO GOMES", "Palestra de Abertura",],
["ANA JULIA PESSANHA MANHÃES", "Palestra de Abertura",],
["OSMANE PESSANHA RIBEIRO", "Palestra de Abertura",],
["KAIO LUCAS ANDRADE BARRETO", "Palestra de Abertura",],
["LUCIANO CORDEIRO DE OLIVEIRA", "Palestra de Abertura",],
["ELAINE RODRIGUES FIGUEIREDO GONÇALVES", "Palestra de Abertura",],
["SABRINA SOUZA DE ALMEIDA AMARAL", "Palestra de Abertura",],
["ANA FLÁVIA BOVI BADARÓ", "Palestra de Abertura",],
["WALACE VIEIRA BASTOS", "Palestra de Abertura",],
["MAÍRA SOARES HENRIQUES", "Palestra de Abertura",],
["LEIDIANE MIGUEL TEIXEIRA", "Palestra de Abertura",],
["DANIELA BALDUINO DE SOUZA VIEIRA", "Palestra de Abertura",],
["TARSILA MARIA DA SILVA MORAES", "Palestra de Abertura",],
["RAYANE ALVES DE LIMA", "Palestra de Abertura",],
["KETLYNN PASSOS ALVARENGA", "Palestra de Abertura",],
["KARLA RANGEL RIBEIRO", "Palestra de Abertura",],
["THAÍS APARECIDA DE CASTRO PALERMO", "Palestra de Abertura",],
["LILIAN CRISTINA CLEMENTE DOS SANTOS ORGANISTA", "Palestra de Abertura",],
["MURILO MAIA SILVA", "Palestra de Abertura",],
["JHULLY RANGEL DE OLIVEIRA GONÇALVES", "Palestra de Abertura",],
["PRISCILA GOMES CHAGAS", "Palestra de Abertura",],
["ANDERSON ALMEIDA", "Palestra de Abertura",],
["ANDRÉ LUIS MOURA", "Palestra de Abertura",],
["LUÍS MAGNO DE SOUZA RIBEIRO", "Palestra de Abertura",],
["RÔMULO DE FREITAS SOUSA SANTOS", "Palestra de Abertura",],
["FABRICIO BARRETO GOMES", "Palestra de Abertura",],
["CÉLIDA LUNA MENDIVIL", "Palestra de Abertura",],
["YANDRA DA SILVA FLOR", "Palestra de Abertura",],
["DANILO DOS SANTOS PAULINO CERQUEIRA", "Palestra de Abertura",],
["LIANA", "Palestra de Abertura",],
["ZARLAS MACIEL DE SOUZA", "Palestra de Abertura",],
["ROMULO DA SILVA VIANA", "Palestra de Abertura",],
["WANDER GOMES NEY", "Palestra de Abertura",],
["LIZ KELLY DE SOUZA PIRES ALVARENGA", "Palestra de Abertura",],
["ANGELA MACIEL PUGLIA", "Palestra de Abertura",],
["STEFANY SILVA VIEIRA DE ALMEIDA", "Palestra de Abertura",],
["PATRÍCIA DE ABREU MONTEIRO AZEVEDO", "Palestra de Abertura",],
["STEFÂNIA DE OLIVEIRA SILVA", "Palestra de Abertura",],
["SANDRA DE MIRANDA SOARES", "Palestra de Abertura",],
["MARCELIA PAES CARVALHO", "Palestra de Abertura",],
["GUILHERME MELO MIRANDA", "Palestra de Abertura",],
["GISELY RIBEIRO GRAÇA", "Palestra de Abertura",],
["ANA LETÍCIA RANGEL GOMES", "Palestra de Abertura",],
["CLAUDIA DE OLIVEIRA", "Palestra de Abertura",],
["DANIELA PEREIRA VERSIEUX", "Palestra de Abertura",],
["CÁTIA VALÉRIA DA SILVA AMARAL", "Palestra de Abertura",],
["GABRIELA DO ROSARIO SILVA", "Palestra de Abertura",],
["PEDRO LUÍS REIS PRADO", "Palestra de Abertura",],
["KAILANE ISAIAS FONTES", "Palestra de Abertura",],
["RAQUEL DO ROSARIO SILVA", "Palestra de Abertura",],
["BRUNA SILVA DO NASCIMENTO", "Palestra de Abertura",],
["FERNANDA BARRETO DE ALBUQUERQUE EBRAHIM", "Palestra de Abertura",],
["LARISSA DE SOUSA MOREIRA", "Palestra de Abertura",],
["LINDALVA MARTINS FLORES DE SÁ", "Palestra de Abertura",],
["ANTHONY RODRIGUES DOS SANTOS", "Palestra de Abertura",],
["KÍSSILA FRANÇA LIMA", "Palestra de Abertura",],
["JACKELINE BARCELOS CORRÊA", "Palestra de Abertura",],
["ESTELLE VIEIRA", "Palestra de Abertura",],
["CAMILA DO ROSARIO SILVA BARRETO", "Palestra de Abertura",],
["FRANCIELI GONÇALVES FRANCESCHINI", "Palestra de Abertura",],
["ANDERSON MARTINS OLIVEIRA JÚNIOR", "Palestra de Abertura",],
["KÍSSILA DA CONCEIÇÃO RIBEIRO", "Palestra de Abertura",],
["LUIZ CLÁUDIO DA SILVA VELASCO", "Palestra de Abertura",],
["DENNIS BENÍCIO HERCULANO CESÁRIO DE BARROS", "Palestra de Abertura",],
["KATHLLEN RIBEIRO FARIA", "Palestra de Abertura",],
["SAIONARA ROSA DA CRUZ", "Palestra de Abertura",],
["GILMAR SANTOS COSTA", "Palestra de Abertura",],
["DENISE CRISTINA BARRETO SILVA", "Palestra de Abertura",],
["MARIA LUIZA RODRIGUES DEFANTE", "Palestra de Abertura",],
["LARA FABIANA LUZ MALHEIRO", "Palestra de Abertura",],
["ANDRÉ PIZETTA ALTOÉ", "Palestra de Abertura",],
["ROMULO MUSSEL", "Palestra de Abertura",],
["PAULO GEDEÃO BARROSO GOMES JÚNIOR", "Palestra de Abertura",],
["TIAGO DOS SANTOS PACHECO", "Palestra de Abertura",],
["THAIS ELISA BARCELOS ABREU", "Palestra de Abertura",],
["CÍNTIA MORAIS VIEIRA", "Palestra de Abertura",],
["MILENA BERNARDO IMBELONI", "Palestra de Abertura",],
["IVAN SOUZA DE ABREU", "Palestra de Abertura",],
["MARÍLIA GONÇALVES DUTRA DA SILVA", "Palestra de Abertura",],
["DAVID VASCONCELOS CORRÊA DA SILVA", "Palestra de Abertura",],
]

minicursos = [
["amaro Pacheco Ferreira Junior","Manutenção Automo", ],
["Arthur Silva André Carvalho","Manutenção Automo", ],
["Bernardo Schmidt Faquer","Manutenção Automo", ],
["Caio Fábio Chrisóstomo da Silva","Manutenção Automo", ],
["Carlos Antonio Pessanha da Silva","Manutenção Automo", ],
["Danyel Henriques Velasco Cristosan","Manutenção Automo", ],
["Dara Lucia ribeiro da silva","Manutenção Automo", ],
["douglas alves","Manutenção Automo", ],
["Felipe Guimarães de Souza","Manutenção Automo", ],
["Flávio Junio de Carvalho Neto","Manutenção Automo", ],
["FRANCIELI GONÇALVES FRANCESCHINI","Manutenção Automo", ],
["Gabriel Ribeiro Santos","Manutenção Automo", ],
["Gustavo Alex Flores Parrela","Manutenção Automo", ],
["Isaias Freitas da Silva","Manutenção Automo", ],
["Jorge Amado II","Manutenção Automo", ],
["Josué Nascimento Rocha","Manutenção Automo", ],
["Kauã Evandro Soares Vieira Fernandes","Manutenção Automo", ],
["Leonardo Perez Siqueira Mota","Manutenção Automo", ],
["Lucas Martins Silva","Manutenção Automo", ],
["Maria Eduarda Borges Lobo Miranda","Manutenção Automo", ],
["Matheus Ribeiro Simões","Manutenção Automo", ],
["Matheus Vieira Barcelos Rezende","Manutenção Automo", ],
["Milton Barbosa Torres Filho","Manutenção Automo", ],
["Ralf Cruz Mateus","Manutenção Automo", ],
["Roman'na Alves da Conceição dos Santos","Manutenção Automo", ],
["Sthefany Pessanha Risso dos Santos","Manutenção Automo", ],
["Maria Luiza Marchetti dos Santos","Manutenção Automo", ],
["Leandro da Silva Viana","Manutenção Automo", ],
["Natielen Nogueira Ribeiro","Manutenção Automo", ],
["Anthony Rodrigues dos Santos","Manutenção Automo", ],
["Ketlynn Passos Alvarenga", "Controle e monitoramento de poluentes",],
["Bárbara Velasco Holender", "Controle e monitoramento de poluentes",],
["Pehtra Eloah Bastos Gomes", "Controle e monitoramento de poluentes",],
["Tainá Pessoa Araújo", "Controle e monitoramento de poluentes",],
["Aliny Rangel de Andrade", "Controle e monitoramento de poluentes",],
["Rafael Gomes da Silva", "Controle e monitoramento de poluentes",],
["Roberta Ribeiro Rangel", "Controle e monitoramento de poluentes",],
["Jullya Borges de Sá", "Controle e monitoramento de poluentes",],
["dagles ferreira lopes", "Controle e monitoramento de poluentes",],
["Bruno Barbosa Manhães e Rangel Lima", "Controle e monitoramento de poluentes",],
["Braulio Ramos Ferreira Siqueira", "Controle e monitoramento de poluentes",],
["LETICIA MOTA DE OLIVEIRA", "Controle e monitoramento de poluentes",],
["Rebeca Brasil Fonseca Vieira", "Controle e monitoramento de poluentes",],
["Roman'na Alves da Conceição dos Santos", "Controle e monitoramento de poluentes",],
["Ana Karolina Fernandes de Souza", "Controle e monitoramento de poluentes",],
["Lívia Pessanha Gonçalves Santana", "Controle e monitoramento de poluentes",],
["Yasmim Barbosa Padilha de Souza", "Controle e monitoramento de poluentes",],
["Thayna Gomes Cruz", "Controle e monitoramento de poluentes",],
["Luanna da Silva Souza", "Controle e monitoramento de poluentes",],
["MAYARA DA SILVA SOARES", "Controle e monitoramento de poluentes",],
["Amanda de Souza Eiras", "Controle e monitoramento de poluentes",],
["Tamires Gomes Silva", "Controle e monitoramento de poluentes",],
["Amanda José da Silva Seares", "Controle e monitoramento de poluentes",],
["Letycia de Almeida Leal", "Controle e monitoramento de poluentes",],
["Sabrina Souza de Almeida Amaral", "Controle e monitoramento de poluentes",],
["WAGNER MACHADO DA SILVA", "Controle e monitoramento de poluentes",],
["Osmane Pessanha Ribeiro", "Controle e monitoramento de poluentes",],
["Lívia da Silva Carvalho", "Controle e monitoramento de poluentes",],
["Samyra Corrêa Albino", "Controle e monitoramento de poluentes",],
["Bernardo Schmidt Faquer", "Controle e monitoramento de poluentes",],
["Gabriela Alves Benjamin", "Controle e monitoramento de poluentes",],
["Klarissa Leite Kreile", "Controle e monitoramento de poluentes",],
["Ana Julia Pessanha Manhães", "Controle e monitoramento de poluentes",],
["RAYSSA VIEIRA RIOS SARDINHA RANGEL", "Controle e monitoramento de poluentes",],
["Kethellin Barreto Teixeira", "Controle e monitoramento de poluentes",],
["Lorena Neves Brandao", "Controle e monitoramento de poluentes",],
["Ana Clara Silva Faria", "Controle e monitoramento de poluentes",],
["Caroline Klem de Castro", "Controle e monitoramento de poluentes",],
["Aline Ferreira de Andrade", "Controle e monitoramento de poluentes",],
["Karina da Silva Pereira Azeredo", "Controle e monitoramento de poluentes",],
["Luana Rangel de Souza", "Controle e monitoramento de poluentes",],
["Luiza Silva do Nascimento", "Controle e monitoramento de poluentes",],
["Layra de Oliveira Silva", "Controle e monitoramento de poluentes",],
["Ana Paula Pereira", "Controle e monitoramento de poluentes",],
["Láyza Ignácio da Silva Costa", "Controle e monitoramento de poluentes",],
["Flávia Tatiana Fortunato Ferreira", "Controle e monitoramento de poluentes",],
["Andrew Anderson Carvalho de abreu", "Controle e monitoramento de poluentes",],
["Ana Rebeka Damasceno da Silva Teixeira", "Controle e monitoramento de poluentes",],
["Danilo Dos Santos Paulino Cerqueira", "Controle e monitoramento de poluentes",],
["Diná Corrêa Lessa Tostes", "Controle e monitoramento de poluentes",],
["Elizama Pereira de Souza", "Controle e monitoramento de poluentes",],
["Vitor Guimarães Correia", "Controle e monitoramento de poluentes",],
["Patrícia Amancio carvalho batista", "Controle e monitoramento de poluentes",],
["LETICIA DA SILVA FERREIRA", "Controle e monitoramento de poluentes",],
["Analice Andretti Gomes", "Controle e monitoramento de poluentes",],
["Tatiana dos santos pessanha", "Controle e monitoramento de poluentes",],
["Daniele do Nascimento Aprijo", "Controle e monitoramento de poluentes",],
["Ana Luiza Ferreira do Rosário", "Controle e monitoramento de poluentes",],
["MARCIO DE FREITAS AZEVEDO", "Controle e monitoramento de poluentes",],
["Janaina Monteiro da Silva", "Controle e monitoramento de poluentes",],
["Arthur Figueira Marini", "Controle e monitoramento de poluentes",],
["Luiz Elpídio Moser Martíns Manhães", "Controle e monitoramento de poluentes",],
["Jhulia Rabelo Constantino", "Controle e monitoramento de poluentes",],
["Isabella Mota Raphael de Lima Arêas", "Controle e monitoramento de poluentes",],
["Beatriz Gomes Peixoto Paes", "Controle e monitoramento de poluentes",],
["Mayana da Silva Rosa", "Controle e monitoramento de poluentes",],
["LUIZ HENRIQUE GOMES MORAES", "Controle e monitoramento de poluentes",],
["Helena Palmeira Dias", "Controle e monitoramento de poluentes",],
["Karla Rangel Ribeiro", "Ações e estratégias gerenciais",],
["Lucas Machado Galante Rufino", "Ações e estratégias gerenciais",],
["Michelle Cristina de Queiroz Pontes", "Ações e estratégias gerenciais",],
["Gisely Ribeiro Graça", "Ações e estratégias gerenciais",],
["Letícia Barros de Oliveira", "Ações e estratégias gerenciais",],
["Sthefany Pessanha Risso dos Santos", "Ações e estratégias gerenciais",],
["Thaís Campos da conceição", "Ações e estratégias gerenciais",],
["Raiany Ramos Rosa", "Ações e estratégias gerenciais",],
["Lorenna Mendes Caetano", "Ações e estratégias gerenciais",],
["Tatiana Azevedo Gomes", "Ações e estratégias gerenciais",],
["Sarah de Sousa Corrêa", "Ações e estratégias gerenciais",],
["Vera Lúcia Souza das Chagas Nogueira", "Ações e estratégias gerenciais",],
["Anne Karolyne Rocha Miranda", "Ações e estratégias gerenciais",],
["Larissa Soares de Oliveira Precioso", "Ações e estratégias gerenciais",],
["Letícia da Silva Adolfo Simões", "Ações e estratégias gerenciais",],
["Fabrícia Martins Sales", "Ações e estratégias gerenciais",],
["Sara Vilaça Faria", "Ações e estratégias gerenciais",],
["Mariana Venancio dos Santos", "Ações e estratégias gerenciais",],
["Mariana Rodrigues de Freitas", "Ações e estratégias gerenciais",],
["Nathália Abreu Barbosa", "Ações e estratégias gerenciais",],
["Thaís Aparecida de Castro Palermo", "Ações e estratégias gerenciais",],
["Rayane Jesus de Sá", "Ações e estratégias gerenciais",],
["Alessandra Rocha Melo", "Ações e estratégias gerenciais",],
["Jeane Fernandes Soares", "Ações e estratégias gerenciais",],
["Celida LunaMendivil", "Ações e estratégias gerenciais",],
["kathelin Rose Nunes Cabral Monteiro", "Ações e estratégias gerenciais",],
["Maria Luiza Freitas Pereira da Silva", "Ações e estratégias gerenciais",],
["Pamella Jane Ribeiro Pessanha", "Ações e estratégias gerenciais",],
["Karen Elesbão Bernardo", "Ações e estratégias gerenciais",],
["Fabiola de Souza da Silva Ferreira", "Ações e estratégias gerenciais",],
["Zarlas Maciel de Souza", "Ações e estratégias gerenciais",],
["Larissa Teodoro França", "Ações e estratégias gerenciais",],
["Thais Curvello dos Santos", "Composição, arranjo e direção musical",],
["Douglas Gomes Silva da Cruz", "Composição, arranjo e direção musical",],
["Saulo Queiroz Nascimento", "Composição, arranjo e direção musical",],
["Ana Carolina dos Santos Souza", "Composição, arranjo e direção musical",],
["Moisés Faria Carvalho", "Composição, arranjo e direção musical",],
["Marcos André da Silva Gomes", "Composição, arranjo e direção musical",],
["Karine Costa da Silva", "Composição, arranjo e direção musical",],
["Karen Machado da Silva", "Composição, arranjo e direção musical",],
["Maria Esther Machado Peres da Silva", "Composição, arranjo e direção musical",],
["Sthefanie Paula Gomes Lobo Matos", "Composição, arranjo e direção musical",],
["Jessica Kely Soares de Meneses", "Composição, arranjo e direção musical",],
["Samara Tobias de Castro", "Composição, arranjo e direção musical",],
["GIULIA AZEVEDO PASCHOAL", "Composição, arranjo e direção musical",],
["Lorenna Mendes Caetano", "Composição, arranjo e direção musical",],
["Alexandre Vinícius couto da Rocha", "Composição, arranjo e direção musical",],
["Kathllen Ribeiro Faria", "Composição, arranjo e direção musical",],
["Ruan Gomes Ribeiro Alves", "Composição, arranjo e direção musical",],
["Estelle Vieira Gomes de Oliveira", "Composição, arranjo e direção musical",],
["Victor Hugo Ayres de Freitas", "Composição, arranjo e direção musical",],
["Cristiano Matos de Oliveira", "Composição, arranjo e direção musical",],
["Katiana Rodrigues da Silva", "Composição, arranjo e direção musical",],
["Rosissara de Sousa Pinheiro", "Composição, arranjo e direção musical",],
["Rafaella Vasconcelos Silva de Araújo Nogueira", "Composição, arranjo e direção musical",],
["Maria Luiza Rodrigues Defante", "Composição, arranjo e direção musical",],
["Joyce Salgado Mercadante Scot", "Composição, arranjo e direção musical",],
["Aline Oliveira", "Elaboração, aplicação",],
["Ana Carolina Laurindo Paulo", "Elaboração, aplicação",],
["Ana Paula Fernandes Klem", "Elaboração, aplicação",],
["Ana Paula Pereira", "Elaboração, aplicação",],
["Anete Ribeiro da Gama", "Elaboração, aplicação",],
["Cínthia Pinheiro Lisbôa", "Elaboração, aplicação",],
["Ellen Bernardes de Lima", "Elaboração, aplicação",],
["Fabricio Barreto Gomes", "Elaboração, aplicação",],
["Gisele Milare", "Elaboração, aplicação",],
["Gustavo Landim Soffiati", "Elaboração, aplicação",],
["Jayrlândia Coutinho de Souza", "Elaboração, aplicação",],
["José Elias da Silva Justo", "Elaboração, aplicação",],
["Juliana Santos Alves de Souza", "Elaboração, aplicação",],
["Junio Rangel Botelho", "Elaboração, aplicação",],
["Karla Rangel Ribeiro", "Elaboração, aplicação",],
["Kethellin Barreto Teixeira", "Elaboração, aplicação",],
["Ketlynn Passos Alvarenga", "Elaboração, aplicação",],
["Lara de Souza Gonçalves", "Elaboração, aplicação",],
["Leticia Fernandes de Vasconcellos de Jesus", "Elaboração, aplicação",],
["Luanna da Silva Souza", "Elaboração, aplicação",],
["Luciana Valadão Vasconcelos Alves", "Elaboração, aplicação",],
["Lucimar da Silva Pereira Junior", "Elaboração, aplicação",],
["Luiza Silva do Nascimento", "Elaboração, aplicação",],
["Marcely Pereira Ribeiro", "Elaboração, aplicação",],
["Maria Clara Ribeiro Miranda", "Elaboração, aplicação",],
["Maria Eduarda Moço do Espírito Santo", "Elaboração, aplicação",],
["NEILA FABER DA SILVA PRUCOLI", "Elaboração, aplicação",],
["Nilson Coutinho Gomes Néto", "Elaboração, aplicação",],
["PRISCILA DOS SANTOS CAETANO DE FREITAS", "Elaboração, aplicação",],
["Rafael Castro", "Elaboração, aplicação",],
["Roberta Ribeiro Rangel", "Elaboração, aplicação",],
["Rogério de Avellar Campos Cordeiro", "Elaboração, aplicação",],
["SANDRA DE MIRANDA SOARES", "Elaboração, aplicação",],
["Talita Neme Lima Santos Lopes", "Elaboração, aplicação",],
["Tania Mara Gomes da Silva", "Elaboração, aplicação",],
["Thaís Aparecida de Castro Palermo", "Elaboração, aplicação",],
["WAGNER MACHADO DA SILVA", "Elaboração, aplicação",],
["Tiago Tadeu Ribeiro Sousa", "Elaboração, aplicação",],
["Marília Gonçalves Dutra da Silva","Introdução à Linguagem Python",],
["Caio Fábio Chrisóstomo da Silva","Introdução à Linguagem Python",],
["Jorge Amado","Introdução à Linguagem Python",],
["Danyel Henriques Velasco Cristosan","Introdução à Linguagem Python",],
["Thiago Lopes Ferreira","Introdução à Linguagem Python",],
["Kauã Evandro Soares Vieira Fernandes","Introdução à Linguagem Python",],
["Janaina Bentes Coelho","Introdução à Linguagem Python",],
["Gustavo Alex Flores Parrela","Introdução à Linguagem Python",],
["Liz Kelly de Souza Pires Alvarenga","Introdução à Linguagem Python",],
["Kaio Lucas Andrade Barreto","Introdução à Linguagem Python",],
["Arthur Silva André Carvalho", "Introdução à Linguagem Python",],
["Rafael Siqueira Pessanha", "Introdução à Linguagem Python",],
["Luiz Henrique Gomes Moraes", "Introdução à Linguagem Python",],
["Giovana Gandra Riscado","Introdução à Linguagem Python",],
["Elias Alves Soares","Introdução à Linguagem Python",],
["Larissa Rangel Moreira","Introdução à Linguagem Python",],
["Mariana Aguiar Massote","Introdução à Linguagem Python",],
["Rayane Alves de Lima","Introdução à Linguagem Python",],
["Leandro da Silva Viana","Introdução à Linguagem Python",],
["Roman'na Alves da Conceição dos Santos","Introdução à Linguagem Python",],
["Nayara Chriscilan de Oliveira Peixoto","Introdução à Linguagem Python",],
["Leidiane Miguel Teixeira","Introdução à Linguagem Python",],
["Ralf Cruz Mateus","Introdução à Linguagem Python",],
["Lara Lysandro de Albernaz Lírio","Introdução à Linguagem Python",],
["Christiano Carvalho Leal","Introdução à Linguagem Python",],
["Myrella Campos de Oliveira","Introdução à Linguagem Python",],
["Tiago Ritter Pessanha","Introdução à Linguagem Python",],
["Marcos Bruno Pereira Campos","Introdução à Linguagem Python",],
["Caio Nogueira Menezes","Introdução à Linguagem Python",],
["Mateus dos Santos Vieira Castelo","Introdução à Linguagem Python",],
["Kaique Marques França Vieira", "O que devo fazer para controlar minha vida",],
["Pedro Fonseca Machado da Costa", "O que devo fazer para controlar minha vida",],
["TAUAN GUILHERME DOS SANTOS BENEVIDES", "O que devo fazer para controlar minha vida",],
["LETICIA MOTA DE OLIVEIRA", "O que devo fazer para controlar minha vida",],
["Thayna Gomes Cruz", "O que devo fazer para controlar minha vida",],
["PEDRO LUIS REIS PRADO", "O que devo fazer para controlar minha vida",],
["Mayara kelly Silva Alves", "O que devo fazer para controlar minha vida",],
["Anny karollyne maricá dos Santos", "O que devo fazer para controlar minha vida",],
["Bruna Silva do Nascimento", "O que devo fazer para controlar minha vida",],
["Lindalva Martins Flores de Sá", "O que devo fazer para controlar minha vida",],
["Ricardo Belmiro Vieira", "O que devo fazer para controlar minha vida",],
["Matheus De Oliveira Carvalho Nunes", "O que devo fazer para controlar minha vida",],
["Ana Paula Pereira", "O que devo fazer para controlar minha vida",],
["Tamara dos Santos Freitas", "O que devo fazer para controlar minha vida",],
["Maria Eduarda Moço do Espírito Santo", "O que devo fazer para controlar minha vida",],
["Maria Clara Ribeiro Miranda", "O que devo fazer para controlar minha vida",],
["Ketlynn Passos Alvarenga", "O que devo fazer para controlar minha vida",],
["Gustavo Landim Soffiati", "O que devo fazer para controlar minha vida",],
["Osmane Pessanha Ribeiro", "O que devo fazer para controlar minha vida",],
["Priscila Gomes Chagas", "O que devo fazer para controlar minha vida",],
["Maria Ester Ferreira de Souza", "O que devo fazer para controlar minha vida",],
["emanuele da silva goulart fernandes", "O que devo fazer para controlar minha vida",],
["Beatriz Gomes Peixoto Paes", "O que devo fazer para controlar minha vida",],
["RAQUEL FIDELIS DA SILVA", "O que devo fazer para controlar minha vida",],
["Janaina Monteiro da Silva", "O que devo fazer para controlar minha vida",],
["Ana Carolina Laurindo Paulo", "O que devo fazer para controlar minha vida",],
["Gabriel da Silva Alves", "O que devo fazer para controlar minha vida",],
["José Elias da Silva Justo", "O que devo fazer para controlar minha vida",],
["Ana Karolina Fernandes de Souza", "O que devo fazer para controlar minha vida",],
["Láyza Ignácio da Silva Costa", "O que devo fazer para controlar minha vida",],
["Lorena Neves Brandao", "O que devo fazer para controlar minha vida",],
["Marllon Batista da Conceição", "O que devo fazer para controlar minha vida",],
["Laura Arêas Bernardo Avelino", "O que devo fazer para controlar minha vida",],
["Fabricio Barreto Gomes", "O que devo fazer para controlar minha vida",],
["Kethellin Barreto Teixeira", "O que devo fazer para controlar minha vida",],
["Mirla Ferreira Lima", "O que devo fazer para controlar minha vida",],
["Rafael Gomes da Silva", "O que devo fazer para controlar minha vida",],
["Tatiana dos santos pessanha", "O que devo fazer para controlar minha vida",],
["Mariana Nunes Mendonça", "O que devo fazer para controlar minha vida",],
["Keven Lucas Notenos Medeiros", "O que devo fazer para controlar minha vida",],
["Cíntia Neves Reis", "O que devo fazer para controlar minha vida",],
["Mariana Martins De Azevedo", "O que devo fazer para controlar minha vida",],
["Braulio Ramos Ferreira Siqueira", "O que devo fazer para controlar minha vida",],
["Marcely Pereira Ribeiro", "O que devo fazer para controlar minha vida",],
["Bianca Asseff dos Reis", "O que devo fazer para controlar minha vida",],
["Andrew anderson carvalho de abreu", "O que devo fazer para controlar minha vida",],
["Débora Rebel e Carvalho", "O que devo fazer para controlar minha vida",],
["Mayara Santos Silva", "O que devo fazer para controlar minha vida",],
["Laís Nogueira Santos", "O que devo fazer para controlar minha vida",],
["Letícia Siqueira Aquino Ribeiro de Castro", "O que devo fazer para controlar minha vida",],
["REGIS BARRETO AMARAL", "O que devo fazer para controlar minha vida",],
["Luanna da Silva Souza", "O que devo fazer para controlar minha vida",],
["Suzanne de Oliveira Rosário", "O que devo fazer para controlar minha vida",],
["AMILTON DOUGLAS FERREIRA DE ARAUJO", "Saúde do Homem: políticas, ações",],
["Letícia Barros de Oliveira", "Saúde do Homem: políticas, ações",],
["Anne Karolyne Rocha Miranda", "Saúde do Homem: políticas, ações",],
["Michelle Cristina de Queiroz Pontes", "Saúde do Homem: políticas, ações",],
["Karen Elesbão Bernardo", "Saúde do Homem: políticas, ações",],
["Ingryd de Oliveira Martins Barboza", "Saúde do Homem: políticas, ações",],
["Talita dos Santos Silva", "Saúde do Homem: políticas, ações",],
["Thaís Campos da conceição", "Saúde do Homem: políticas, ações",],
["Zarlas Maciel de Souza", "Saúde do Homem: políticas, ações",],
["Fabrícia Martins Sales", "Saúde do Homem: políticas, ações",],
["Sara Vilaça Faria", "Saúde do Homem: políticas, ações",],
["Larissa Teodoro França", "Saúde do Homem: políticas, ações",],
["MARCELIA PAES CARVALHO", "Saúde do Homem: políticas, ações",],
["Nathália Abreu Barbosa", "Saúde do Homem: políticas, ações",],
["Giselle Natalina Sousa da Silva", "Saúde do Homem: políticas, ações",],
["Vera Lúcia Souza das Chagas Nogueira", "Saúde do Homem: políticas, ações",],
["Juliana Pereira Cabral", "Saúde do Homem: políticas, ações",],
["Andressa da Silva Medeiros", "Saúde do Homem: políticas, ações",],
["Raiany Ramos Rosa", "Saúde do Homem: políticas, ações",],
["Mariana Venancio dos Santos", "Saúde do Homem: políticas, ações",],
["CÉLIDA LUNA MENDIVIL", "Saúde do Homem: políticas, ações",],
["Sarah de Sousa Corrêa", "Saúde do Homem: políticas, ações",],
["Leidiane Miguel Teixeira", "Saúde do Homem: políticas, ações",],
["Mayara kelly Silva Alves", "Saúde do Homem: políticas, ações",],
["Isaias Freitas da Silva", "Saúde do Homem: políticas, ações",],
["Heliza de Melo Castro", "Saúde do Homem: políticas, ações",],
["Larissa Soares de Oliveira Precioso", "Saúde do Homem: políticas, ações",],
["Ana Carolina Souza Almeida Nogueira", "Top Tips for ENEM",],
["Ana Clara Soares Sales", "Top Tips for ENEM",],
["Ana Cristina Souza de Lima", "Top Tips for ENEM",],
["Bruna Silva do Nascimento", "Top Tips for ENEM",],
["Darfiny Alves Nogueira", "Top Tips for ENEM",],
["Ellen Bernardes de Lima", "Top Tips for ENEM",],
["Helena Almeida de Menezes", "Top Tips for ENEM",],
["Isabelle da Silva Cruz Gomes", "Top Tips for ENEM",],
["Julia Marques Veloso Faria", "Top Tips for ENEM",],
["Jullya Borges de Sá", "Top Tips for ENEM",],
["Letycia de Almeida Leal", "Top Tips for ENEM",],
["Maria Luiza Rodrigues Defante", "Top Tips for ENEM",],
["Mariana Gomes Da Silva Campos", "Top Tips for ENEM",],
["Mariana Martins De Azevedo", "Top Tips for ENEM",],
["Milena Bernardo Imbeloni", "Top Tips for ENEM",],
["Sabrina Souza de Almeida Amaral", "Top Tips for ENEM",],
["Sulamita Sales", "Top Tips for ENEM",],
["Thalita Lopes Peixoto", "Top Tips for ENEM",],
["Juliana Santos Alves de Souza", "A educação ambiental como tema transversal",],
["Sabrina Souza de Almeida Amaral", "A educação ambiental como tema transversal",],
["Yasmin da Silva Ribeiro", "A educação ambiental como tema transversal",],
["Lara de Souza Gonçalves", "A educação ambiental como tema transversal",],
["Amanda José da Silva Seares", "A educação ambiental como tema transversal",],
["Sulamita Sales", "A educação ambiental como tema transversal",],
["Leidiane Miguel Teixeira", "A educação ambiental como tema transversal",],
["Tamara dos Santos Freitas", "A educação ambiental como tema transversal",],
["Ana Julia Pessanha Manhães", "A educação ambiental como tema transversal",],
["Maria Flávia Monteiro Nogueira", "A educação ambiental como tema transversal",],
["Patrícia Amancio carvalho batista", "A educação ambiental como tema transversal",],
["Caio Fábio Chrisóstomo da Silva", "Cabeamento estruturado",],
["Leandro da Silva Viana", "Cabeamento estruturado",],
["João Pedro Araújo Almeida", "Cabeamento estruturado",],
["Gabriel Ribeiro Santos", "Cabeamento estruturado",],
["Pedro Almeida Nogueira", "Cabeamento estruturado",],
["Kaio Lucas Andrade Barreto", "Cabeamento estruturado",],
["Nacib Adib Maciel Tarabai", "Cabeamento estruturado",],
["Kayo de Souza Bastos", "Cabeamento estruturado",],
["Jorge Amado II", "Cabeamento estruturado",],
["William dos Santos Inácio", "Cabeamento estruturado",],
["Stefânia de Oliveira Silva", "Cabeamento estruturado",],
["Fernanda Barreto de Albuquerque Ebrahim", "Cabeamento estruturado",],
["Talita Neme Lima Santos Lopes", "Cabeamento estruturado",],
["Talita dos Santos Silva", "Cabeamento estruturado",],
["Kauan Pires Ribeiro", "Cabeamento estruturado",],
["Francisco de Assis Tavares da Silva Matos", "Cabeamento estruturado",],
["Lívia Maria Gomes Paiva Pereira", "Cabeamento estruturado",],
["Lucas de Souza Gonçalves", "Cabeamento estruturado",],
["Laís Nogueira Santos", "Como ser Lean", ],
["Flávia Tatiana Fortunato Ferreira", "Como ser Lean", ],
["Kethellin Barreto Teixeira", "Como ser Lean", ],
["Iasmin Rodrigues Rosa", "Como ser Lean", ],
["Aline Ferreira de Andrade", "Como ser Lean", ],
["Júlia Reis Braga", "Como ser Lean", ],
["Romulo da Silva Viana", "Como ser Lean", ],
["Ana Rebeka Damasceno da Silva Teixeira", "Como ser Lean", ],
["Lorena Neves Brandao", "Como ser Lean", ],
["Yasmim Barbosa Padilha de Souza", "Como ser Lean", ],
["CARMEN DANIELLE DE SOUZA PAES PESSANHA", "Como ser Lean", ],
["Arthur Figueira Marini", "Contaminação de ecossistemas",],
["Sérgio Júnior", "Contaminação de ecossistemas",],
["Bárbara Velasco Holender", "Contaminação de ecossistemas",],
["Beatriz Gomes Peixoto Paes", "Contaminação de ecossistemas",],
["Milena Bernardo Imbeloni", "Contaminação de ecossistemas",],
["CÍNTIA NEVES REIS", "Contaminação de ecossistemas",],
["Marcela Rocha Rainha", "Contaminação de ecossistemas",],
["Daniele do Nascimento Aprijo", "Contaminação de ecossistemas",],
["Larissa Rangel Moreira", "Contaminação de ecossistemas",],
["Letycia de Almeida Leal", "Contaminação de ecossistemas",],
["Daniel Gomes Ferreira", "Contaminação de ecossistemas",],
["Sabrina Souza de Almeida Amaral", "Contaminação de ecossistemas",],
["Bruno Barbosa Manhães e Rangel Lima", "Contaminação de ecossistemas",],
["Kethellin Barreto Teixeira", "Contaminação de ecossistemas",],
["dagles ferreira lopes", "Contaminação de ecossistemas",],
["Ana Clara Coelho Beiral", "Contaminação de ecossistemas",],
["MATHEUS GOMES TAVARES", "Contaminação de ecossistemas",],
["Maryana Cristina Ramos Araújo", "Contaminação de ecossistemas",],
["Eliliane Vasconcelos Corrêa Almada", "Contaminação de ecossistemas",],
["Ana Cristina Souza De Lima", "Contaminação de ecossistemas",],
["Ellen Bernardes de Lima", "Contaminação de ecossistemas",],
["Gleyciane Siqueira", "Contaminação de ecossistemas",],
["Diná Corrêa Lessa Tostes", "Contaminação de ecossistemas",],
["Janaina Monteiro da Silva", "Contaminação de ecossistemas",],
["MARCIO DE FREITAS AZEVEDO", "Contaminação de ecossistemas",],
["Vanessa da Silva Ferreira Rangel", "Contaminação de ecossistemas",],
["Amanda José da Silva Seares", "Contaminação de ecossistemas",],
["Ana Paula Pereira", "Contaminação de ecossistemas",],
["Lorena Neves Brandão", "Contaminação de ecossistemas",],
["Patrícia Amancio carvalho batista", "Contaminação de ecossistemas",],
["Ketlynn Passos Alvarenga", "Da Arte Barroca à Contemporânea",],
["Maria Angelica Oliveira Vellasco", "Da Arte Barroca à Contemporânea",],
["Anny karollyne maricá dos Santos", "Da Arte Barroca à Contemporânea",],
["Jullya Borges de Sá", "Da Arte Barroca à Contemporânea",],
["Gustavo Landim Soffiati", "Da Arte Barroca à Contemporânea",],
["Mariana Gomes da Silva Campos", "Da Arte Barroca à Contemporânea",],
["Estelle Vieira Gomes de Oliveira", "Da Arte Barroca à Contemporânea",],
["Cínthia Pinheiro Lisbôa", "Da Arte Barroca à Contemporânea",],
["Ingrid Maia Nanjara", "Da Arte Barroca à Contemporânea",],
["Luisa Silva Rocha", "Da Arte Barroca à Contemporânea",],
["Larissa de Paula Viana Souza", "Da Arte Barroca à Contemporânea",],
["Ingrid reis pessanha de miranda", "Da Arte Barroca à Contemporânea",],
["Aída Maria Jorge Ribeiro", "Da Arte Barroca à Contemporânea",],
["Nicoly Fonseca Gomes", "Da Arte Barroca à Contemporânea",],
["Vinicius da Silva Martins", "Da Arte Barroca à Contemporânea",],
["Fernanda Lopes Barroso", "Da Arte Barroca à Contemporânea",],
["Nathálya Rodrigues de Sá Ribeiro", "Da Arte Barroca à Contemporânea",],
["Giullia Santos Silva Pessanha de Macedo", "Da Arte Barroca à Contemporânea",],
["Laisa dos Santos Caetano", "Da Arte Barroca à Contemporânea",],
["Maria Luiza Rodrigues Defante", "Da Arte Barroca à Contemporânea",],
["Lindalva Martins Flores de Sá", "Da Arte Barroca à Contemporânea",],
["Suzanne de Oliveira Rosário", "Da Arte Barroca à Contemporânea",],
["Sérgio Rangel Risso", "Da Arte Barroca à Contemporânea",],
["Larissa Andrade Do Espirito Santo", "Da Arte Barroca à Contemporânea",],
["Pedro Costa dos Santos", "Da Arte Barroca à Contemporânea",],
["JOAO GABRIEL SILVA ANDRE", "Da Arte Barroca à Contemporânea",],
["Iasmin Rodrigues Rosa", "Da Arte Barroca à Contemporânea",],
["Marcelly Martins da Cruz", "Da Arte Barroca à Contemporânea",],
["Tania Mara Gomes da Silva", "Da Arte Barroca à Contemporânea",],
["Leidiane Miguel Teixeira", "Da Arte Barroca à Contemporânea",],
["Laura Falcão dos Santos Nogueira", "Da Arte Barroca à Contemporânea",],
["Luiza Silva do Nascimento", "Dos and Don", ],
["Ana Carolina Laurindo Paulo", "Dos and Don", ],
["Jorge Amado", "Dos and Don", ],
["Amanda José da Silva Seares", "Dos and Don", ],
["Kauã Evandro Soares Vieira Fernandes", "Dos and Don", ],
["Thaynara da Silva Francisco", "Dos and Don", ],
["Bianca Asseff", "Dos and Don", ],
["Ana Cristina Souza de Lima", "Dos and Don", ],
["Ellen Bernardes de Lima", "Dos and Don", ],
["Dayse Kethellen Nascimento da Silva", "Dos and Don", ],
["Aída Maria Jorge Ribeiro", "Dos and Don", ],
["Ketlynn Passos Alvarenga", "Dos and Don", ],
["Darichelle Cristina Rocha Vilaça", "Dos and Don", ],
["Nathália Abreu Barbosa", "Dos and Don", ],
["Maria Eduarda Moço do Espírito Santo", "Dos and Don", ],
["ADRIANA BARBOSA MENEZES", "História da Enfermagem", ],
["Andrielly da Silva Jorge", "História da Enfermagem", ],
["Anne Karolyne Rocha Miranda", "História da Enfermagem", ],
["Bianca Teodora de Souza", "História da Enfermagem", ],
["CÉLIDA LUNA MENDIVIL", "História da Enfermagem", ],
["Fabiola de souza da silva ferreira", "História da Enfermagem", ],
["GABRIEL ALVES BONFIM", "História da Enfermagem", ],
["Karen Elesbão Bernardo", "História da Enfermagem", ],
["KARLA RANGEL RIBEIRO", "História da Enfermagem", ],
["Keren lemos morais", "História da Enfermagem", ],
["KETHELEN LUIZ PESSANHA PITOTE", "História da Enfermagem", ],
["Larissa Soares de Oliveira Precioso", "História da Enfermagem", ],
["Larissa Teodoro França", "História da Enfermagem", ],
["Letícia Barros de Oliveira", "História da Enfermagem", ],
["Letícia da Silva Adolfo Simões", "História da Enfermagem", ],
["Mariana Venancio dos Santos", "História da Enfermagem", ],
["Mayara kelly Silva Alves", "História da Enfermagem", ],
["Mirla Ferreira Lima", "História da Enfermagem", ],
["Nathália Abreu Barbosa", "História da Enfermagem", ],
["Rafaela Cruz Azeredo", "História da Enfermagem", ],
["Raiany Ramos Rosa", "História da Enfermagem", ],
["Rayane Jesus de Sá", "História da Enfermagem", ],
["Sarah de Sousa Corrêa", "História da Enfermagem", ],
["Thaís Aparecida de Castro Palermo", "História da Enfermagem", ],
["Thaís Campos da conceição", "História da Enfermagem", ],
["Zarlas Maciel de Souza", "História da Enfermagem", ],
["Ruan Gomes Ribeiro Alves", "Música, Cultura e Sociedade",],
["THAIS CURVELLO DOS SANTOS", "Música, Cultura e Sociedade",],
["Douglas Gomes Silva da Cruz", "Música, Cultura e Sociedade",],
["Moisés Faria Carvalho", "Música, Cultura e Sociedade",],
["JEFFERSON CAVALARO GOUVEA", "Música, Cultura e Sociedade",],
["GIULIA AZEVEDO PASCHOAL", "Música, Cultura e Sociedade",],
["Samara Tobias de Castro", "Música, Cultura e Sociedade",],
["Bruna Silva do Nascimento", "Música, Cultura e Sociedade",],
["Lindalva Martins Flores de Sá", "Música, Cultura e Sociedade",],
["Fernanda Beatriz Rodrigues Defante", "Música, Cultura e Sociedade",],
["Ingrid Maia Nanjara", "Música, Cultura e Sociedade",],
["Everton Luis Nascimento da Silva", "Música, Cultura e Sociedade",],
["Fabricio Barreto Gomes", "Música, Cultura e Sociedade",],
["Rosissara de Sousa Pinheiro", "Música, Cultura e Sociedade",],
["Diogo Rebel e Carvalho", "Música, Cultura e Sociedade",],
["Gustavo Landim Soffiati", "Música, Cultura e Sociedade",],
]